version: "2"
linters:
  default: all
  disable:
    - wsl
    - cyclop
    - gochecknoinits
    - wrapcheck
    - testpackage
    - goconst
    - exhaustruct
    - err113
    - lll
  settings:
    varnamelen:
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
    funcorder:
      struct-method: false
    tagalign:
      sort: false
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/relvacode/ca-portal
            - github.com/jessevdk/go-flags
            - github.com/smallstep/certificates
            - github.com/coreos/go-oidc/v3/oidc
            - github.com/google/uuid
            - github.com/uptrace/bunrouter
            - golang.org/x/oauth2
            - software.sslmate.com/src/go-pkcs12